name: electronica
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  page_transition: ^1.1.4
  simple_animations: ^1.3.3
  rxdart: 0.22.2
  flutter_upi: ^0.0.2
  provider: ^4.3.1
  transparent_image: 1.0.0
  firebase_auth: ^0.16.1
  firebase: ^7.3.0
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  google_sign_in: ^4.5.1
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/
  

  
  fonts:
    - family: NoeMedium
      fonts:
        - asset: assets/images/noeDisplay_Medium.ttf
    - family: Ubantu
      fonts:
        - asset: assets/images/ubantu_bold.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/images/ubuntu.ttf
    - family: PlayFair
      fonts:
        - asset: assets/images/playfair_display.ttf
  
  